/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_xjtu_cs_cyx_qshield_execution_QShieldSGXEnclave */

#ifndef _Included_edu_xjtu_cs_cyx_qshield_execution_QShieldSGXEnclave
#define _Included_edu_xjtu_cs_cyx_qshield_execution_QShieldSGXEnclave
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_xjtu_cs_cyx_qshield_execution_QShieldSGXEnclave
 * Method:    ACPolicyApplied
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_xjtu_cs_cyx_qshield_execution_QShieldSGXEnclave_ACPolicyApplied
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
